name: "Build Armbian for Orange Pi 3B"
on:
  workflow_dispatch:

jobs:
  build-armbian:
    runs-on: ubuntu-latest
    steps:
      - uses: armbian/build@v24.08
        with:
          armbian_token:    "${{ secrets.GITHUB_TOKEN }}"
          armbian_release:  "bookworm"
          armbian_target:   "build"
          armbian_board:    "orangepi3b"
          armbian_ui:       "server"
